name: flowbite_ui
description: "Unofficial Flutter package for Flowbite UI Kit (made by Themesberg)"
version: 0.0.5
homepage: https://github.com/hanmajid/flowbite_ui
issue_tracker: https://github.com/hanmajid/flowbite_ui/issues
repository: https://github.com/hanmajid/flowbite_ui
funding:
  - https://github.com/sponsors/hanmajid

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flowbite_icons: ^0.0.3
  flowbite_illustrations: ^0.4.0
  flutter:
    sdk: flutter

  material_ui: any
dev_dependencies:
  dot_shorthand_converter: ^0.0.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
