// Copyright 2026 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flowbite_ui/flowbite_ui.dart';
import 'package:flutter/material.dart';

class FlowbiteTheme {
  static final light = ThemeData.light().copyWith(
    extensions: [lightThemeColors],
  );

  static final lightThemeColors = FlowbiteColorsExtension(
    textWhite: FlowbiteColors.textWhite,
    textBlack: FlowbiteColors.textBlack,
    textHeading: FlowbiteColors.textHeading,
    textBody: FlowbiteColors.textBody,
    textBodySubtle: FlowbiteColors.textBodySubtle,
    textFgBrandSubtle: FlowbiteColors.textFgBrandSubtle,
    textFgBrand: FlowbiteColors.textFgBrand,
    textFgBrandStrong: FlowbiteColors.textFgBrandStrong,
    textFgSuccess: FlowbiteColors.textFgSuccess,
    textFgSuccessStrong: FlowbiteColors.textFgSuccessStrong,
    textFgDanger: FlowbiteColors.textFgDanger,
    textFgDangerStrong: FlowbiteColors.textFgDangerStrong,
    textFgWarningSubtle: FlowbiteColors.textFgWarningSubtle,
    textFgWarning: FlowbiteColors.textFgWarning,
    textFgYellow: FlowbiteColors.textFgYellow,
    textFgInfo: FlowbiteColors.textFgInfo,
    textFgDisabled: FlowbiteColors.textFgDisabled,
    textFgPurple: FlowbiteColors.textFgPurple,
    textFgCyan: FlowbiteColors.textFgCyan,
    textFgIndigo: FlowbiteColors.textFgIndigo,
    textFgPink: FlowbiteColors.textFgPink,
    textFgLime: FlowbiteColors.textFgLime,
    bgWhite: FlowbiteColors.bgWhite,
    bgNeutralPrimarySoft: FlowbiteColors.bgNeutralPrimarySoft,
    bgNeutralPrimary: FlowbiteColors.bgNeutralPrimary,
    bgNeutralPrimaryMedium: FlowbiteColors.bgNeutralPrimaryMedium,
    bgNeutralPrimaryStrong: FlowbiteColors.bgNeutralPrimaryStrong,
    bgNeutralSecondarySoft: FlowbiteColors.bgNeutralSecondarySoft,
    bgNeutralSecondary: FlowbiteColors.bgNeutralSecondary,
    bgNeutralSecondaryMedium: FlowbiteColors.bgNeutralSecondaryMedium,
    bgNeutralSecondaryStrong: FlowbiteColors.bgNeutralSecondaryStrong,
    bgNeutralTertiarySoft: FlowbiteColors.bgNeutralTertiarySoft,
    bgNeutralTertiary: FlowbiteColors.bgNeutralTertiary,
    bgNeutralTertiaryMedium: FlowbiteColors.bgNeutralTertiaryMedium,
    bgNeutralQuaternary: FlowbiteColors.bgNeutralQuaternary,
    bgNeutralQuaternaryMedium: FlowbiteColors.bgNeutralQuaternaryMedium,
    bgGray: FlowbiteColors.bgGray,
    bgBrandSofter: FlowbiteColors.bgBrandSofter,
    bgBrandSoft: FlowbiteColors.bgBrandSoft,
    bgBrandMedium: FlowbiteColors.bgBrandMedium,
    bgBrand: FlowbiteColors.bgBrand,
    bgBrandStrong: FlowbiteColors.bgBrandStrong,
    bgSuccessSoft: FlowbiteColors.bgSuccessSoft,
    bgSuccessMedium: FlowbiteColors.bgSuccessMedium,
    bgSuccess: FlowbiteColors.bgSuccess,
    bgSuccessStrong: FlowbiteColors.bgSuccessStrong,
    bgDangerSoft: FlowbiteColors.bgDangerSoft,
    bgDangerMedium: FlowbiteColors.bgDangerMedium,
    bgDanger: FlowbiteColors.bgDanger,
    bgDangerStrong: FlowbiteColors.bgDangerStrong,
    bgWarningSoft: FlowbiteColors.bgWarningSoft,
    bgWarningMedium: FlowbiteColors.bgWarningMedium,
    bgWarning: FlowbiteColors.bgWarning,
    bgWarningStrong: FlowbiteColors.bgWarningStrong,
    bgDarkStrong: FlowbiteColors.bgDarkStrong,
    bgDark: FlowbiteColors.bgDark,
    bgDisabled: FlowbiteColors.bgDisabled,
    bgPurple: FlowbiteColors.bgPurple,
    bgSky: FlowbiteColors.bgSky,
    bgTeal: FlowbiteColors.bgTeal,
    bgPink: FlowbiteColors.bgPink,
    bgCyan: FlowbiteColors.bgCyan,
    bgFuschia: FlowbiteColors.bgFuschia,
    bgIndigo: FlowbiteColors.bgIndigo,
    bgOrange: FlowbiteColors.bgOrange,
    borderDark: FlowbiteColors.borderDark,
    borderBuffer: FlowbiteColors.borderBuffer,
    borderBufferMedium: FlowbiteColors.borderBufferMedium,
    borderBufferStrong: FlowbiteColors.borderBufferStrong,
    borderMuted: FlowbiteColors.borderMuted,
    borderLightSubtle: FlowbiteColors.borderLightSubtle,
    borderLight: FlowbiteColors.borderLight,
    borderLightMedium: FlowbiteColors.borderLightMedium,
    borderBaseSoft: FlowbiteColors.borderBaseSoft,
    borderBase: FlowbiteColors.borderBase,
    borderBaseMedium: FlowbiteColors.borderBaseMedium,
    borderBaseStrong: FlowbiteColors.borderBaseStrong,
    borderSuccessSubtle: FlowbiteColors.borderSuccessSubtle,
    borderSuccess: FlowbiteColors.borderSuccess,
    borderDangerSubtle: FlowbiteColors.borderDangerSubtle,
    borderDanger: FlowbiteColors.borderDanger,
    borderWarningSubtle: FlowbiteColors.borderWarningSubtle,
    borderWarning: FlowbiteColors.borderWarning,
    borderBrandSubtle: FlowbiteColors.borderBrandSubtle,
    borderBrandLight: FlowbiteColors.borderBrandLight,
    borderBrand: FlowbiteColors.borderBrand,
    borderPurple: FlowbiteColors.borderPurple,
    borderOrange: FlowbiteColors.borderOrange,
    borderDarkSubtle: FlowbiteColors.borderDarkSubtle,
  );

  static final dark = ThemeData.dark().copyWith(extensions: [_darkThemeColors]);

  static final _darkThemeColors = FlowbiteColorsExtension(
    textWhite: FlowbiteColors.textWhite,
    textBlack: FlowbiteColors.textBlack,
    textHeading: FlowbiteColors.textHeadingDark,
    textBody: FlowbiteColors.textBodyDark,
    textBodySubtle: FlowbiteColors.textBodySubtleDark,
    textFgBrandSubtle: FlowbiteColors.textFgBrandSubtleDark,
    textFgBrand: FlowbiteColors.textFgBrandDark,
    textFgBrandStrong: FlowbiteColors.textFgBrandStrongDark,
    textFgSuccess: FlowbiteColors.textFgSuccessDark,
    textFgSuccessStrong: FlowbiteColors.textFgSuccessStrongDark,
    textFgDanger: FlowbiteColors.textFgDangerDark,
    textFgDangerStrong: FlowbiteColors.textFgDangerStrongDark,
    textFgWarningSubtle: FlowbiteColors.textFgWarningSubtleDark,
    textFgWarning: FlowbiteColors.textFgWarningDark,
    textFgYellow: FlowbiteColors.textFgYellowDark,
    textFgInfo: FlowbiteColors.textFgInfoDark,
    textFgDisabled: FlowbiteColors.textFgDisabledDark,
    textFgPurple: FlowbiteColors.textFgPurpleDark,
    textFgCyan: FlowbiteColors.textFgCyanDark,
    textFgIndigo: FlowbiteColors.textFgIndigoDark,
    textFgPink: FlowbiteColors.textFgPinkDark,
    textFgLime: FlowbiteColors.textFgLimeDark,
    bgWhite: FlowbiteColors.bgWhite,
    bgNeutralPrimarySoft: FlowbiteColors.bgNeutralPrimarySoftDark,
    bgNeutralPrimary: FlowbiteColors.bgNeutralPrimaryDark,
    bgNeutralPrimaryMedium: FlowbiteColors.bgNeutralPrimaryMediumDark,
    bgNeutralPrimaryStrong: FlowbiteColors.bgNeutralPrimaryStrongDark,
    bgNeutralSecondarySoft: FlowbiteColors.bgNeutralSecondarySoftDark,
    bgNeutralSecondary: FlowbiteColors.bgNeutralSecondaryDark,
    bgNeutralSecondaryMedium: FlowbiteColors.bgNeutralSecondaryMediumDark,
    bgNeutralSecondaryStrong: FlowbiteColors.bgNeutralSecondaryStrongDark,
    bgNeutralTertiarySoft: FlowbiteColors.bgNeutralTertiarySoftDark,
    bgNeutralTertiary: FlowbiteColors.bgNeutralTertiaryDark,
    bgNeutralTertiaryMedium: FlowbiteColors.bgNeutralTertiaryMediumDark,
    bgNeutralQuaternary: FlowbiteColors.bgNeutralQuaternaryDark,
    bgNeutralQuaternaryMedium: FlowbiteColors.bgNeutralQuaternaryMediumDark,
    bgGray: FlowbiteColors.bgGrayDark,
    bgBrandSofter: FlowbiteColors.bgBrandSofterDark,
    bgBrandSoft: FlowbiteColors.bgBrandSoftDark,
    bgBrandMedium: FlowbiteColors.bgBrandMediumDark,
    bgBrand: FlowbiteColors.bgBrandDark,
    bgBrandStrong: FlowbiteColors.bgBrandStrongDark,
    bgSuccessSoft: FlowbiteColors.bgSuccessSoftDark,
    bgSuccessMedium: FlowbiteColors.bgSuccessMediumDark,
    bgSuccess: FlowbiteColors.bgSuccessDark,
    bgSuccessStrong: FlowbiteColors.bgSuccessStrongDark,
    bgDangerSoft: FlowbiteColors.bgDangerSoftDark,
    bgDangerMedium: FlowbiteColors.bgDangerMediumDark,
    bgDanger: FlowbiteColors.bgDangerDark,
    bgDangerStrong: FlowbiteColors.bgDangerStrongDark,
    bgWarningSoft: FlowbiteColors.bgWarningSoftDark,
    bgWarningMedium: FlowbiteColors.bgWarningMediumDark,
    bgWarning: FlowbiteColors.bgWarningDark,
    bgWarningStrong: FlowbiteColors.bgWarningStrongDark,
    bgDarkStrong: FlowbiteColors.bgDarkStrongDark,
    bgDark: FlowbiteColors.bgDarkDark,
    bgDisabled: FlowbiteColors.bgDisabledDark,
    bgPurple: FlowbiteColors.bgPurpleDark,
    bgSky: FlowbiteColors.bgSkyDark,
    bgTeal: FlowbiteColors.bgTealDark,
    bgPink: FlowbiteColors.bgPinkDark,
    bgCyan: FlowbiteColors.bgCyanDark,
    bgFuschia: FlowbiteColors.bgFuschiaDark,
    bgIndigo: FlowbiteColors.bgIndigoDark,
    bgOrange: FlowbiteColors.bgOrangeDark,
    borderDark: FlowbiteColors.borderDark,
    borderBuffer: FlowbiteColors.borderBufferDark,
    borderBufferMedium: FlowbiteColors.borderBufferMediumDark,
    borderBufferStrong: FlowbiteColors.borderBufferStrongDark,
    borderMuted: FlowbiteColors.borderMutedDark,
    borderLightSubtle: FlowbiteColors.borderLightSubtleDark,
    borderLight: FlowbiteColors.borderLightDark,
    borderLightMedium: FlowbiteColors.borderLightMediumDark,
    borderBaseSoft: FlowbiteColors.borderBaseSoftDark,
    borderBase: FlowbiteColors.borderBaseDark,
    borderBaseMedium: FlowbiteColors.borderBaseMediumDark,
    borderBaseStrong: FlowbiteColors.borderBaseStrongDark,
    borderSuccessSubtle: FlowbiteColors.borderSuccessSubtleDark,
    borderSuccess: FlowbiteColors.borderSuccessDark,
    borderDangerSubtle: FlowbiteColors.borderDangerSubtleDark,
    borderDanger: FlowbiteColors.borderDangerDark,
    borderWarningSubtle: FlowbiteColors.borderWarningSubtleDark,
    borderWarning: FlowbiteColors.borderWarningDark,
    borderBrandSubtle: FlowbiteColors.borderBrandSubtleDark,
    borderBrandLight: FlowbiteColors.borderBrandLightDark,
    borderBrand: FlowbiteColors.borderBrandDark,
    borderPurple: FlowbiteColors.borderPurpleDark,
    borderOrange: FlowbiteColors.borderOrangeDark,
    borderDarkSubtle: FlowbiteColors.borderDarkSubtleDark,
  );
}
